version: '2'
services:
    smarteshop-app:
        image: smarteshop
        external_links:
            - smarteshop-mysql:mysql
            - smarteshop-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/smarteshop?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    smarteshop-mysql:
        extends:
            file: mysql.yml
            service: smarteshop-mysql
    smarteshop-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: smarteshop-elasticsearch
